POST http://0.0.0.0:5001/auth/register
Accept: application/json
Content-Type: application/json

{
  "username": "Camaltra",
  "email": "camaltra@gmail.com",
  "password": "12345"
}

###

GET http://0.0.0.0:5001/users/me
Accept: application/json

###

PATCH http://0.0.0.0:5001/users/2
Accept: application/json
Content-Type: application/json

{
  "username": "JUNGLE TOP 1"
}

###

GET http://0.0.0.0:5001/users/me
Accept: application/json

###

POST http://0.0.0.0:5001/auth/logout
Accept: application/json

###

POST http://0.0.0.0:5001/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin"
}

###

GET http://0.0.0.0:5001/users/2
Accept: application/json

###

PATCH http://0.0.0.0:5001/users/2
Accept: application/json
Content-Type: application/json

{
  "username": "Camaltra"
}

###

GET http://0.0.0.0:5001/users/2
Accept: application/json

###

DELETE http://0.0.0.0:5001/users/2
Accept: application/json

###

GET http://0.0.0.0:5001/users/
Accept: application/json

###

POST http://0.0.0.0:5001/auth/logout
Accept: application/json

###