POST http://0.0.0.0:5001/auth/register
Accept: application/json
Content-Type: application/json

{
  "username": "Camaltra",
  "email": "camaltra@gmail.com",
  "password": "12345"
}

###

GET http://0.0.0.0:5001/user/me
Accept: application/json

###

POST http://0.0.0.0:5001/auth/logout
Accept: application/json

###

POST http://0.0.0.0:5001/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "camaltra@gmail.com",
  "password": "1234"
}

###

GET http://0.0.0.0:5001/user/me
Accept: application/json


###

POST http://0.0.0.0:5001/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "camaltra@gmail.com",
  "password": "12345"
}

###

GET http://0.0.0.0:5001/user/me
Accept: application/json

###

POST http://0.0.0.0:5001/auth/logout
Accept: application/json

###